Feature/consume with high lever consumer
M6Web/KafkaBundle pull request #2
Opened 2016-12-12 17:48 UTC by NastasiaSaby

In progress. Don't comment it please for the moment.

2016-12-13 16:10 UTC, twdmnd commented on DependencyInjection/Configuration.php
> +                                    ->defaultValue(array())
Indentation

2016-12-13 16:49 UTC, twdmnd commented on DependencyInjection/Configuration.php
> +                                    ->defaultValue(array())
Indentation

2016-12-13 16:49 UTC, twdmnd commented on DependencyInjection/Configuration.php
> +                                    ->normalizeKeys(false)
Indentation

2016-12-13 16:49 UTC, twdmnd commented on DependencyInjection/Configuration.php
> +                                    ->defaultValue(array())
Indentation

2016-12-13 16:49 UTC, twdmnd commented on DependencyInjection/Configuration.php
> +                                    ->normalizeKeys(false)
Indentation

2016-12-13 16:49 UTC, twdmnd commented on DependencyInjection/Configuration.php
> +                                    ->defaultValue(array())
Indentation

2016-12-13 16:49 UTC, twdmnd commented on DependencyInjection/Configuration.php
> +                                    ->normalizeKeys(false)
Indentation

2016-12-13 16:49 UTC, twdmnd commented on DependencyInjection/M6WebKafkaExtension.php
> +        $entityDefinition
addMethodCall returns entityDefinition, so you can do:
```
$entityDefinition
    ->addMethodCall('addBrokers', [$brokers])
    ->addMethodCall('setLogLevel', [$entity['log_level']]);
```

2016-12-13 16:49 UTC, twdmnd commented on DependencyInjection/M6WebKafkaExtension.php
> +        array_walk($confToSet, function ($confValue, $confIndex) use ($topicConf) {
`array_walk(array_flip($confToSet), $topicConf->set);`

2016-12-13 16:49 UTC, twdmnd commented on DependencyInjection/M6WebKafkaExtension.php
> +        array_walk($confToSet, function ($confValue, $confIndex) use ($rdKafkaConf) {
`array_walk(array_flip($confToSet), $rdKafkaConf->set)`

2016-12-13 16:49 UTC, twdmnd commented on DependencyInjection/M6WebKafkaExtension.php
> +            if ($error === RD_KAFKA_RESP_ERR__ASSIGN_PARTITIONS) {
switch ?

2016-12-13 16:49 UTC, twdmnd commented on IntegrationTests/Units/RdKafkaConsumerManager.php
> +
extra line

2016-12-13 16:49 UTC, twdmnd commented on RdKafkaConsumerManager.php
> +     * @return $this
?

2016-12-13 16:49 UTC, twdmnd commented on RdKafkaConsumerManager.php
> +     * @return $this
?

2016-12-13 16:49 UTC, twdmnd commented on RdKafkaProducerManager.php
> +    /**
New line missing

2016-12-13 16:49 UTC, twdmnd commented on RdKafkaProducerManager.php
> +    protected function produceForEachTopic(string $message, int $partition, string $key = null) : callable
unused $key

2016-12-13 16:49 UTC, twdmnd commented on Tests/Units/RdKafkaConsumerManager.php
> +                ->string($result)
Indentation

2016-12-13 16:49 UTC, twdmnd commented on Tests/Units/RdKafkaConsumerManager.php
> +                ->mock($eventDispatcherMock)
Indentation

2016-12-13 16:49 UTC, twdmnd commented on Tests/Units/RdKafkaConsumerManager.php
> +                ->mock($rdKafkaConsumerMock)
Indentation

2016-12-13 16:49 UTC, twdmnd commented on Tests/Units/RdKafkaProducerManager.php
> +                ->mock($eventDispatcherMock)
Indentation

2016-12-13 16:53 UTC, lnahiro commented on DependencyInjection/Configuration.php
> +                            ->arrayNode('topics')
pas possible de mettre la conf des topics ici ? comme pour le producer

2016-12-13 16:53 UTC, lnahiro commented on DependencyInjection/M6WebKafkaExtension.php
> +            $consumerDefinition = $this->getDefinition('M6Web\Bundle\KafkaBundle\RdKafkaConsumerManager');
ConsumerManager ?

2016-12-13 16:53 UTC, lnahiro commented on DependencyInjection/M6WebKafkaExtension.php
> +            $consumerDefinition->addMethodCall('setRdKafkaKafkaConsumer', [$kafkaConsumer]);
setConsumer ?

2016-12-13 16:53 UTC, lnahiro commented on RdKafkaConsumerManager.php
> +            return 'No more message';
return null ? pour indiquer qu'il n'y a plus de message.

2016-12-13 16:53 UTC, lnahiro commented on RdKafkaConsumerManager.php
> +            return 'Time out';
throw exception ?

2016-12-13 16:53 UTC, lnahiro commented on RdKafkaProducerManager.php
> +            $topic->produce($partition, 0, $message);
commentaire pour expliquer pourquoi le zero en deuxième paramètres

2016-12-13 17:01 UTC, twdmnd commented on DependencyInjection/M6WebKafkaExtension.php
> +            throw new \Exception($error);
Why not a less generic exception ?

2016-12-13 17:01 UTC, twdmnd commented on IntegrationTests/Units/DependencyInjection/M6WebKafkaExtension.php
> +            ->variable($producer->produce('\O/'))
Not tested

2016-12-13 17:01 UTC, twdmnd commented on IntegrationTests/Units/DependencyInjection/M6WebKafkaExtension.php
> +            ->variable($message1->payload)
`->variable(($consumer->consume())->payload)`

2016-12-13 17:01 UTC, twdmnd commented on IntegrationTests/Units/DependencyInjection/M6WebKafkaExtension.php
> +        $parameterBag = new ParameterBag(array('kernel.debug' => true));
array() is so old 😄

2016-12-13 17:01 UTC, twdmnd commented on DependencyInjection/Configuration.php
> +                                    ->defaultValue(array())
`->defaultValue([])`

2016-12-13 17:01 UTC, twdmnd commented on DependencyInjection/Configuration.php
> +                                    ->defaultValue(array())
->defaultValue([])

2016-12-13 17:01 UTC, twdmnd commented on DependencyInjection/Configuration.php
> +                                    ->defaultValue(array())
->defaultValue([])

2016-12-13 17:01 UTC, twdmnd commented on DependencyInjection/Configuration.php
> +                                            ->defaultValue(array())
->defaultValue([])

2016-12-13 17:01 UTC, twdmnd commented on IntegrationTests/Units/RdKafkaConsumerManager.php
> +
extra line

2016-12-13 17:01 UTC, twdmnd commented on RdKafkaConsumerManager.php
> +        if ($message->err === RD_KAFKA_RESP_ERR__PARTITION_EOF) {
switch ?

2016-12-13 17:02 UTC, fabdsp requested changes

2016-12-13 17:02 UTC, fabdsp commented on DependencyInjection/M6WebKafkaExtension.php
> +            $producerDefinition = $this->getDefinition('M6Web\Bundle\KafkaBundle\RdKafkaProducerManager');
Can we use a parameter ? to overload this class ?

2016-12-13 17:02 UTC, fabdsp commented on DependencyInjection/M6WebKafkaExtension.php
> +            $consumerDefinition = $this->getDefinition('M6Web\Bundle\KafkaBundle\RdKafkaConsumerManager');
Can we use a parameter ? to overload this class ?

2016-12-13 17:02 UTC, fabdsp commented on DependencyInjection/M6WebKafkaExtension.php
> +            $kafkaConsumer = new \RdKafka\KafkaConsumer($conf);
Can we configure this class name ?

2016-12-13 17:02 UTC, fabdsp commented on DependencyInjection/M6WebKafkaExtension.php
> +    protected function setProducerManager(array $entity, Definition $entityDefinition)
configProducerManager ? or why not getProducerManager with the getDefinition inside and all the addMethodCall ?

2016-12-13 17:02 UTC, fabdsp commented on README.md
> +It means that in the configuration for a producer you will have to specify the brokers, topics and optionnaly the log level and the strategy partitioner.
optionally

2016-12-13 17:02 UTC, fabdsp commented on RdKafkaConsumerManager.php
> +            return 'No more message';
Maybe null ? or we can set a reason somewhere ?

2016-12-13 17:02 UTC, fabdsp commented on RdKafkaConsumerManager.php
> +            return 'Time out';
null ? or we can set a reason somewhere ?

2016-12-14 08:08 UTC, NastasiaSaby commented on RdKafkaConsumerManager.php
> +            return 'Time out';
I have thought about sending back the null object message directly from the rdKafka, but finally I chose another option. Can we discuss about this point?

2016-12-14 08:10 UTC, NastasiaSaby commented on DependencyInjection/M6WebKafkaExtension.php
> +            $consumerDefinition = $this->getDefinition('M6Web\Bundle\KafkaBundle\RdKafkaConsumerManager');
@fabdsp It was possible. Then, I thought it was weird. So I removed this option. Can we discuss about this point?

2016-12-14 08:11 UTC, NastasiaSaby commented on DependencyInjection/M6WebKafkaExtension.php
> +            $kafkaConsumer = new \RdKafka\KafkaConsumer($conf);
@fabdsp I don't understand :blush:

2016-12-14 09:19 UTC, NastasiaSaby commented on RdKafkaConsumerManager.php
> +            return 'Time out';
Yes, I will let the null RdKakfa\Message object

2016-12-14 09:36 UTC, NastasiaSaby commented on DependencyInjection/M6WebKafkaExtension.php
> +            if ($error === RD_KAFKA_RESP_ERR__ASSIGN_PARTITIONS) {
I find it ugly, but i guess it is not a good answer. So I changed it.

2016-12-16 15:29 UTC, fabdsp approved these changes
Sinon 👍

2016-12-16 15:29 UTC, fabdsp commented on DependencyInjection/M6WebKafkaExtension.php
>          $rdKafkaConf->setRebalanceCb($this->handlePartitionsAssignment());
j'avais raté, mais ce n'est pas génant que cette méthode, dans l'extension, soit appelé pour autre chose que la config et lors du run ? Une méthode static dans une autre class ?

2016-12-16 15:29 UTC, fabdsp commented on RdKafkaConsumerManager.php
> +            $this->rdKafkaKafkaConsumer->commit($message);
On veut forcément de l'auto commit ? ça ne pourrait pas etre un param de consume ? et ajouter une méthode de commit dans cette class pour l'auto commit à false ? Mais j'ai peut-être raté un truc.

2016-12-19 12:47 UTC, fabdsp commented
test this please

2016-12-19 13:49 UTC, gmillet commented on Tests/Units/RdKafkaConsumerManager.php
> +                ->object($result)
Useless ?

2016-12-19 13:49 UTC, twdmnd commented on Tests/Units/RdKafkaConsumerManager.php
> +                ->object($result)
Useless ?

2016-12-19 15:17 UTC, NastasiaSaby commented on Tests/Units/RdKafkaConsumerManager.php
> +                ->object($result)
Yes

2016-12-19 15:17 UTC, NastasiaSaby commented on Tests/Units/RdKafkaConsumerManager.php
> +                ->object($result)
Yes

2016-12-19 15:49 UTC, fabdsp commented on .travis.yml
> +  - sudo make all -j 5 && sudo make install
make all sans le -j 5

2016-12-19 15:49 UTC, fabdsp approved these changes

2016-12-19 16:01 UTC, Oliboy50 requested changes

2016-12-19 16:01 UTC, Oliboy50 commented on .travis.yml
> +  - cd /home/travis/build/M6Web/KafkaBundle
is this possible to use `TRAVIS_BUILD_DIR` instead of this path?

2016-12-19 16:01 UTC, NastasiaSaby commented on .travis.yml
> +  - cd /home/travis/build/M6Web/KafkaBundle
Of cours

2016-12-19 16:06 UTC, Oliboy50 approved these changes

2016-12-19 16:06 UTC, Oliboy50 commented on .travis.yml
> +  - cd /home/travis/build/M6Web/KafkaBundle
thanks :)

2016-12-20 08:24 UTC, lnahiro commented on DependencyInjection/M6WebKafkaExtension.php
> +            $producerDefinition->addMethodCall('setRdKafkaProducer', [$rdKafkaProducer]);
setProducer ?

2016-12-20 08:24 UTC, lnahiro commented on DependencyInjection/M6WebKafkaExtension.php
> +            $consumerManager->addMethodCall('setRdKafkaKafkaConsumer', [$kafkaConsumer]);
setConsumer ?

2016-12-20 08:24 UTC, lnahiro commented on Event/EventLog.php
> +class EventLog extends SymfonyEvent
KafkaEvent ?

2016-12-20 08:24 UTC, lnahiro commented on Resources/config/services.yml
> +    m6_web_kafka.producer.class: 'M6Web\Bundle\KafkaBundle\ProducerManager'
unused ?

2016-12-20 16:52 UTC, merged